version: '3.8'

services:
  statusdeck_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data: